In [33]:
import pandas as pd

In [34]:
csv_path = 'youtube_data/jre_data_2025-01-22.csv'

In [35]:
df = pd.read_csv(csv_path)

In [36]:
df.columns

Index(['Title', 'Publish Date', 'Duration', 'Tags', 'Category', 'Guest Name',
       'View Counts', 'Like Counts', 'Count Date'],
      dtype='object')

In [37]:
df[df['Duration'] > 15000].count()

Title           23
Publish Date    23
Duration        23
Tags            23
Category        23
Guest Name      23
View Counts     23
Like Counts     23
Count Date      23
dtype: int64

In [38]:
titles = df['Title']

In [40]:
titles.count()

3327

In [42]:
df.rename(columns={'episode_name': 'Title', 'Category':'ID'})

,Title,Publish Date,Duration,Tags,ID,Guest Name,View Counts,Like Counts,Count Date
0,Joe Rogan Experience #2260 - Lex Fridman,2025-01-22T18:00:22Z,12080.0,"['Joe Rogan Experience', 'JRE', 'Joe', 'Rogan'...",22,Lex Fridman,24019,1417,2025-01-22T18:00:22Z
1,Joe Rogan Experience #2259 - Thomas Campbell,2025-01-17T18:00:46Z,10061.0,"['Joe Rogan Experience', 'JRE', 'Joe', 'Rogan'...",22,Thomas Campbell,1578684,31097,2025-01-17T18:00:46Z
2,Joe Rogan Experience #2258 - Steven Rinella,2025-01-16T18:00:14Z,10074.0,"['Joe Rogan Experience', 'JRE', 'Joe', 'Rogan'...",22,Steven Rinella,1162294,19939,2025-01-16T18:00:14Z
3,Joe Rogan Experience #2257 - Bryan Callen,2025-01-15T18:00:44Z,9981.0,"['Joe Rogan Experience', 'JRE', 'Joe', 'Rogan'...",22,Bryan Callen,1217079,22745,2025-01-15T18:00:44Z
4,Joe Rogan Experience #2255 - Mark Zuckerberg,2025-01-10T18:00:12Z,10236.0,"['Joe Rogan Experience', 'JRE', 'Joe', 'Rogan'...",22,Mark Zuckerberg,8160413,164812,2025-01-10T18:00:12Z
...,...,...,...,...,...,...,...,...,...
3322,Joe Rogan Experience #336 - Scott Sigler,2013-03-13T04:18:05Z,6510.0,"['Joe Rogan Experience', 'Podcast', 'JRE #336'...",22,Scott Sigler,27788,315,2013-03-13T04:18:05Z
3323,Joe Rogan Experience #335 - Bas Rutten,2013-03-12T03:43:36Z,10269.0,"['Joe Rogan Experience', 'Podcast', 'JRE #335'...",22,Bas Rutten,1044601,7969,2013-03-12T03:43:36Z
3324,"Honey Honey - ""Untitled"" (taken from Joe Rogan...",2013-02-03T21:53:50Z,309.0,"['Honey', 'Untitled', 'JRE', '#299', 'Joe Roga...",10,"""Untitled"" (taken from Joe Rogan Experience #299)",26840,279,2013-02-03T21:53:50Z
3325,"Honey Honey - ""God of Love"" ( taken from the J...",2013-02-03T02:44:13Z,268.0,"['Honey Honey', 'band', 'music', 'Joe Rogan Ex...",10,"""God of Love"" ( taken from the Joe Rogan Exper...",50533,459,2013-02-03T02:44:13Z
3326,"Honey Honey - ""15 Step"" (cover) ( taken from t...",2013-02-03T02:06:04Z,233.0,"['Honey Honey', 'band', 'music', 'Joe Rogan Ex...",10,"""15 Step"" (cover) ( taken from the Joe Rogan E...",43719,415,2013-02-03T02:06:04Z

In [107]:
df.columns

Index(['Title', 'Publish Date', 'Duration', 'Tags', 'Category', 'Guest Name',
       'View Counts', 'Like Counts', 'Count Date'],
      dtype='object')

In [117]:
cleaned_df = df.drop(['Tags'], axis=1)

In [118]:
cleaned_df.columns

Index(['Title', 'Publish Date', 'Duration', 'Category', 'Guest Name',
       'View Counts', 'Like Counts', 'Count Date'],
      dtype='object')

In [119]:
cleaned_df['Duration'] = cleaned_df['Duration'].map(lambda x:x/60/60)

In [120]:
cleaned_df.columns

Index(['Title', 'Publish Date', 'Duration', 'Category', 'Guest Name',
       'View Counts', 'Like Counts', 'Count Date'],
      dtype='object')

,Title,Publish Date,Category,Guest Name,View Counts,Like Counts,Count Date
Duration,,,,,,,
0.014722,JRE Celebrates Episode #2000,2023-06-21T17:50:46Z,22,0,448201,20967,2023-06-21T17:50:46Z
0.020556,Joe (Sort of) Reacts to the Johnny Depp Verdic...,2022-06-02T23:15:10Z2017-07-18T01:29:59Z,44,JRE Toon,4046080,65286,2022-06-02T23:15:10Z2017-07-18T01:29:59Z
0.021944,The Governator Moment - JRE Toon,2017-06-20T22:11:04Z,22,JRE Toon,1043643,20449,2017-06-20T22:11:04Z
0.022778,Toilet Water Moment - JRE Toons,2022-10-03T21:31:06Z,22,JRE Toons,863580,28844,2022-10-03T21:31:06Z
0.023056,Snoop Dogg Whisperer Moment - JRE ToonsJordan ...,2022-08-01T23:20:07Z2022-01-25T18:19:18Z2022-0...,88,JRE ToonsJRE ToonsJRE Toon,5340021,135150,2022-08-01T23:20:07Z2022-01-25T18:19:18Z2022-0...
...,...,...,...,...,...,...,...
5.005556,Joe Rogan Experience - Fight Companion - Octob...,2016-10-22T08:42:13Z,22,"October 21, 2016",450958,3618,2016-10-22T08:42:13Z
5.083056,Joe Rogan Experience #2030 - Protect Our Parks 9,2024-06-27T18:27:31Z,22,Protect Our Parks 9,426436,4320,2024-06-27T18:27:31Z
5.117778,Joe Rogan Experience #2122 - Protect Our Parks 11,2024-03-20T18:00:16Z,22,Protect Our Parks 11,3794133,52465,2024-03-20T18:00:16Z
5.275833,Joe Rogan Experience - Fight Companion - Octo...,2016-10-09T08:37:14Z,22,"October 8, 2016",998510,8727,2016-10-09T08:37:14Z
5.330278,Joe Rogan Experience #1530 - Duncan Trussell,2020-09-01T00:00:01Z,22,Duncan Trussell,8154038,113565,2020-09-01T00:00:01Z

In [128]:
cleaned_df.head()

,Title,Publish Date,Duration,Category,Guest Name,View Counts,Like Counts,Count Date
0,Joe Rogan Experience #2260 - Lex Fridman,2025-01-22T18:00:22Z,3.355556,22,Lex Fridman,24019,1417,2025-01-22T18:00:22Z
1,Joe Rogan Experience #2259 - Thomas Campbell,2025-01-17T18:00:46Z,2.794722,22,Thomas Campbell,1578684,31097,2025-01-17T18:00:46Z
2,Joe Rogan Experience #2258 - Steven Rinella,2025-01-16T18:00:14Z,2.798333,22,Steven Rinella,1162294,19939,2025-01-16T18:00:14Z
3,Joe Rogan Experience #2257 - Bryan Callen,2025-01-15T18:00:44Z,2.772500,22,Bryan Callen,1217079,22745,2025-01-15T18:00:44Z
4,Joe Rogan Experience #2255 - Mark Zuckerberg,2025-01-10T18:00:12Z,2.843333,22,Mark Zuckerberg,8160413,164812,2025-01-10T18:00:12Z

In [129]:
cleaned_df.count()

Title           3327
Publish Date    3327
Duration        3327
Category        3327
Guest Name      2091
View Counts     3327
Like Counts     3327
Count Date      3327
dtype: int64